name: Ansible Galaxy Build
on:
  release:
    types: [published]

jobs:
  build:
    name: Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Build collection
      run: ansible-galaxy collection build .
    - name: Update ansible collection path
      run: |
        export NAMESPACE=$( grep 'namespace:' galaxy.yml | awk '{ print $2 }' )
        export NAME=$( grep 'name:' galaxy.yml | awk '{ print $2 }' )
        export VERSION=$( grep 'version:' galaxy.yml | awk '{ print $2 }' )
        echo "::set-env name=COLLECTION::${NAMESPACE}-${NAME}-${VERSION}.tar.gz"
    - name: Add collection to release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.COLLECTION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
