name: Ansible Galaxy Build
on: [release]

jobs:
  build:
    name: Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Build collection
      run: ansible-galaxy collection build .
